### ISSUE TITLE
propose an implementation for chat form like signup

### ISSUE THREAD

**Issue by ktsuench** [ruhacks/tasks#5]
This is related to task #4 as it will be part of the login portal. Look into how to implement a chat form interface for signups similar to Hack The North's.

**Comment by smehtaca** [comment]
Currently no easy solution to implement a chatbot service for websites. Most services are tailored towards platforms like Twitter, FB Messenger, WhatsApp etc. 

To implement a chatbot solution for the website, we would also need to integrate NLP solutions to handle freeform user input. This could be worked around by implemented selection screens or having one word responses or using some form of keyword lists.

A chatbot service like this would also require a backend API to handle routing and responses and send back JSON.

I need more details on how HacktheNorth's system was setup to be able to come up with a good solution for this issue. If their solution had just a FB messenger style chat head  with presetup statements on the website that guided users through the sign up form that would be not a challenge to implement. If it was a full blow chatbot, it would require a lot more work.

@ktsuench, @jas2996 if you have a video or some images that would be helpful in working on an implementation for this.

**Comment by ktsuench** [comment]
@jas2996 do you know any of the execs on the HackTheNorth team? Specifically the web devs which we could reach out to and ask? The sign up isn't available anymore. :/

**Comment by ktsuench** [comment]
@zsalehi if you have time can you look into this as well?

**Comment by ktsuench** [comment]
https://github.com/space10-community/conversational-form

**Comment by ktsuench** [comment]
Will open another issue to track progress of development.
