### ISSUE TITLE
DreamHost cost and comparison

### ISSUE THREAD

**Issue by ktsuench** [ruhacks/tasks#6]
Give a cost and comparison summary on DreamHost.

- What does it provide?
- For the services/products it provides that we may use, is the cost reasonable?
  - or what are the available plans and specs we can choose from? (_provide link or list_)
- Is it easy to implement those services/products? (_a.k.a. ease of use_)
- In comparison to Heroku:
  - is it easier to set up?
  - is it easier to use?
  - does it provide more services/products to lessen our work?

__Comment summary in this issue.__

**Comment by zsalehi** [comment]
So after doing some research it looks like Dreamhost doesnt actually support different Node Servers and databases very well. We can try it out but I believe it may be more worth to take a look into GOOGLE FIREBASE and GOOGLE CLOUD as it is going to be much easier to handle in the future.
