### ISSUE TITLE
propose an api implementation

### ISSUE THREAD

**Issue by ktsuench** [ruhacks/tasks#9]
Look into how to implement a private api for use between backend and frontend applications.

Possible solution might be to use tokens or look into existing libraries/frameworks to help restrict access to api.

**Comment by ktsuench** [comment]
Almost forgot I recently was looking at [this framework](https://strapi.io/overview). Might be useful for helping us in creating an API.

**Comment by ktsuench** [comment]
# Quick Overview
@smehtaca mentioned [Feathers](https://feathersjs.com/) as another option for building an api. Also, I did another quick sweep of other frameworks out there and came across [this article](https://medium.com/@cabot_solutions/creating-restful-api-with-node-js-hapi-vs-express-ccb97a776c02). In that article, the following frameworks are mentioned: `Hapi`, `Express`, `Koa`, `Meteor`, `Derby`, `Flatiron`, `Mean.IO`, `Mojito`, `Socket`, `Stream`, `Sail.js`, `LoopBack`, `actionHero.js`, and `Restify`.

## Comparing Strapi, Feathers, and LoopBack
I did a quick search on comparing [Strapi and Featherjs](https://www.slant.co/versus/12406/14594/~strapi_vs_feathers). I like how Feather is built on top of Express which is nice, but they do mention that it has a higher learning curve compared to Strapi. Also looked at [LoopBack](https://loopback.io) and it seems nice as it allows for creating _dynamic end-to-end REST APIs_ without little coding involved. However, it seems to have a high learning curve to it (from the couple minutes I skimmed examples). If I get another chance I'd like to spend some more time with Strapi and LoopBack, but I think the framework to use in this case would be Feathers due to it being like middle ground. It's built on top of Express so it's behavior is more like an addition to Express and it seems relatively okay to ease the amount of work required to build an API.

## ;tldr
The three frameworks I took a quick look at were Strapi, Feathers, and LoopBack. I considered how similar they were to the defacto option of Express and ease in creating an API. From a look at their docs and their proposed focuses, __I think Feathers is the best option. We'll move forward with Feathers as it's built on top of Express, can integrate with passportjs, and can help reduce the work in building an API.__

@zsalehi what do you think?

**Comment by zsalehi** [comment]
So I am good with using Feathers. I was thinking instead of passport.js we should use Firebase auth for the backend and database support just for future usability and management. @ktsuench
